"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type UploadState = "idle" | "sending" | "done" | "error";
type Manifest = Record<string, any>;
type Processing = { session_id: string; status: string; manifest?: Manifest };
type HandDetail={tag:string;difficulty:string;note:string}; type LobbyValue={players:string;remaining:string;average_stack:string;prize:string};
type Review = { notes:string; hands:Record<string,string>; lobby:Record<string,string>; rabbits:Record<string,string>; hand_details:Record<string,HandDetail>; lobby_values:Record<string,LobbyValue>; finalized:boolean; favorite:boolean; archived:boolean; session_tags:string[]; updated_at?:string };
type SessionSummary = { id:string;tournament_name?:string;original_filename?:string;created_at:string;processing_status:string;complete_hands:number;partial_hands:number;duration_seconds:number;size_bytes:number;frame_count:number;review_finalized:boolean;favorite:boolean;archived:boolean;session_tags:string[] };
type CurrentUser={email:string;role:"admin"|"player"}; type ManagedUser={email:string;role:"admin"|"player";active:boolean;created_at:string};
const steps = ["probing","segmenting","classifying","detecting_hands","creating_clips","reading_context","clips_ready_for_review"];
const labels: Record<string,string> = {probing:"Validando vídeo",segmenting:"Criando linha do tempo",classifying:"Classificando telas",detecting_hands:"Detectando mãos",creating_clips:"Gerando clipes",reading_context:"Lendo Lobby e Coelho",clips_ready_for_review:"Pronto para revisão",failed:"Falha"};

export default function Home() {
  const [state,setState]=useState<UploadState>("idle"); const [message,setMessage]=useState("Selecione uma gravação encerrada da PPPoker.");
  const [authenticated,setAuthenticated]=useState(false); const [authChecked,setAuthChecked]=useState(false);
  const [currentUser,setCurrentUser]=useState<CurrentUser|null>(null); const [users,setUsers]=useState<ManagedUser[]>([]); const [showUsers,setShowUsers]=useState(false); const [userMessage,setUserMessage]=useState("");
  const [processing,setProcessing]=useState<Processing|null>(null); const [history,setHistory]=useState<SessionSummary[]>([]);
  const [filter,setFilter]=useState("all");
  const [tab,setTab]=useState("overview");
  const [review,setReview]=useState<Review>({notes:"",hands:{},lobby:{},rabbits:{},hand_details:{},lobby_values:{},finalized:false,favorite:false,archived:false,session_tags:[]}); const [reviewStatus,setReviewStatus]=useState("");
  const [sessionSearch,setSessionSearch]=useState(""); const [sessionFilter,setSessionFilter]=useState("all");
  const [sortOrder,setSortOrder]=useState("newest"); const [dateFilter,setDateFilter]=useState("all"); const [favoritesOnly,setFavoritesOnly]=useState(false); const [showArchived,setShowArchived]=useState(false);
  const [sessionTagsText,setSessionTagsText]=useState("");
  async function loadHistory(){const r=await fetch("/v1/sessions",{cache:"no-store"});if(r.ok)setHistory(await r.json())}
  useEffect(()=>{void(async()=>{const r=await fetch("/v1/auth/me",{cache:"no-store"});if(r.ok){setAuthenticated(true);setCurrentUser(await r.json());await loadHistory()}setAuthChecked(true)})()},[]);
  async function loadUsers(){const r=await fetch("/v1/admin/users",{cache:"no-store"});if(r.ok)setUsers(await r.json())}
  async function createInternalUser(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const r=await fetch("/v1/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:data.get("email"),password:data.get("password"),role:data.get("role")})});setUserMessage(r.ok?"Login criado com sucesso":"Não foi possível criar: e-mail duplicado ou dados inválidos");if(r.ok){form.reset();await loadUsers()}}
  async function toggleInternalUser(email:string){const r=await fetch(`/v1/admin/users/${encodeURIComponent(email)}/toggle`,{method:"POST"});setUserMessage(r.ok?"Acesso atualizado":"Não foi possível alterar este acesso");if(r.ok)await loadUsers()}
  async function resetInternalPassword(email:string){const password=window.prompt(`Nova senha para ${email} (mínimo 8 caracteres)`);if(!password)return;const r=await fetch(`/v1/admin/users/${encodeURIComponent(email)}/password`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});setUserMessage(r.ok?"Senha redefinida":"A senha deve ter no mínimo 8 caracteres")}
  async function loadReview(id:string){const r=await fetch(`/v1/sessions/${id}/review`,{cache:"no-store"});if(r.ok){const data=await r.json();setReview(data);setSessionTagsText((data.session_tags??[]).join(", "))}}
  async function saveReview(next:Review){if(!processing)return;setReview(next);setReviewStatus("Salvando…");const r=await fetch(`/v1/sessions/${processing.session_id}/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});setReviewStatus(r.ok?"Decisão salva":"Falha ao salvar");if(r.ok){setReview(await r.json());await loadHistory()}}
  async function decide(section:"hands"|"lobby"|"rabbits",key:string,value:string){await saveReview({...review,[section]:{...review[section],[key]:value}})}
  async function renameSession(){if(!processing)return;const currentName=history.find(x=>x.id===processing.session_id)?.tournament_name??"";const name=window.prompt("Nome do torneio",currentName);if(name===null)return;await fetch(`/v1/sessions/${processing.session_id}/metadata`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tournament_name:name})});await loadHistory()}
  async function retrySession(){if(!processing)return;setReviewStatus("Reenviando para a fila…");const r=await fetch(`/v1/sessions/${processing.session_id}/retry`,{method:"POST"});setReviewStatus(r.ok?"Sessão recolocada na fila":"Não foi possível reprocessar");if(r.ok)void followProcessing(processing.session_id)}
  async function followProcessing(id:string){setTab("overview");void loadReview(id);for(let i=0;i<180;i++){const r=await fetch(`/v1/sessions/${id}/processing`,{cache:"no-store"});if(r.ok){const d=await r.json();setProcessing(d);if(["clips_ready_for_review","failed"].includes(d.status)){await loadHistory();return}}await new Promise(x=>setTimeout(x,1000))}}
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const r=await fetch("/v1/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:d.get("email"),password:d.get("password")})});if(r.ok){setAuthenticated(true);setCurrentUser(await r.json());setMessage("Acesso seguro liberado.");await loadHistory()}else setMessage("E-mail ou senha inválidos.")}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setState("sending");setProcessing(null);setMessage("Enviando gravação com segurança…");try{const r=await fetch("/v1/uploads",{method:"POST",body:new FormData(form)});if(!r.ok)throw new Error();const s=await r.json();form.reset();setState("done");setMessage(`Sessão ${String(s.id).slice(0,8)} recebida.`);void followProcessing(String(s.id));await loadHistory()}catch{setState("error");setMessage("Não foi possível enviar. Tente novamente.")}}
  const manifest=processing?.manifest??{}; const timeline=manifest.timeline??[]; const clips=manifest.clips??[];
  const rabbits=(manifest.rabbit_detection?.candidates??[]).filter((item:any)=>{const text=String(item.ocr?.normalized_text??"").toUpperCase();return text.includes("PAGOU")||text.includes("COELHO")});
  const filtered=useMemo(()=>filter==="all"?timeline:timeline.filter((x:any)=>x.screen_type===filter),[timeline,filter]);
  const hands=manifest.hand_detection?.hands??[]; const completeHands=hands.filter((h:any)=>!h.partial); const quarantine=hands.filter((h:any)=>h.partial);
  const cutoff=dateFilter==="7d"?7:dateFilter==="30d"?30:dateFilter==="90d"?90:0;
  const visibleHistory=history.filter(x=>(sessionFilter==="all"||x.processing_status===sessionFilter)&&(!favoritesOnly||x.favorite)&&(showArchived||!x.archived)&&(!cutoff||Date.now()-new Date(x.created_at).getTime()<=cutoff*86400000)&&`${x.tournament_name??""} ${x.original_filename??""} ${(x.session_tags??[]).join(" ")}`.toLowerCase().includes(sessionSearch.toLowerCase())).sort((a,b)=>sortOrder==="oldest"?+new Date(a.created_at)-+new Date(b.created_at):sortOrder==="hands"?b.complete_hands-a.complete_hands:+new Date(b.created_at)-+new Date(a.created_at));
  const activeHistory=history.filter(x=>!x.archived);const totalHours=activeHistory.reduce((n,x)=>n+x.duration_seconds,0)/3600;const totalHands=activeHistory.reduce((n,x)=>n+x.complete_hands,0);const totalPartial=activeHistory.reduce((n,x)=>n+x.partial_hands,0);const finalizedPercent=activeHistory.length?Math.round(activeHistory.filter(x=>x.review_finalized).length/activeHistory.length*100):0;
  const reviewTargets=completeHands.length+(manifest.lobby_context??[]).length+rabbits.length; const reviewDone=Object.keys(review.hands).length+Object.keys(review.lobby).length+Object.keys(review.rabbits).length; const reviewPercent=reviewTargets?Math.min(100,Math.round(reviewDone/reviewTargets*100)):0;
  const current=Math.max(0,steps.indexOf(processing?.status??""));
  if(!authChecked)return <main><p className="loading">Verificando sessão segura…</p></main>;
  return <main><nav><span className="mark">C</span><strong>Coach IA</strong><span className="badge">PÓS-SESSÃO</span>{currentUser?.role==="admin"&&<button className="user-admin-button" onClick={()=>{setShowUsers(!showUsers);if(!showUsers)void loadUsers()}}>Usuários</button>}{authenticated&&<span className="current-user">{currentUser?.email}</span>}{authenticated&&<button className="logout" onClick={async()=>{await fetch("/v1/auth/logout",{method:"POST"});setAuthenticated(false);setCurrentUser(null);setHistory([]);setProcessing(null)}}>Sair</button>}</nav>
    {!authenticated?<section className="login-shell"><div><p className="eyebrow">PPPOKER · ESTUDO TÉCNICO</p><h1>Sua sessão termina.<br/><span>Seu estudo começa.</span></h1><p className="lead">Análise somente depois do jogo, com evidência antes de qualquer conclusão.</p></div><form key="login" onSubmit={login}><label>E-mail administrativo<input name="email" type="email" autoComplete="username" required/></label><label>Senha<input name="password" type="password" autoComplete="current-password" required/></label><button>Entrar com segurança</button><p className="status">{message}</p></form></section>:
    <><header className="dash-head"><div><p className="eyebrow">CENTRAL DE REVISÃO</p><h1>Dashboard de sessões</h1><p>Envie, acompanhe e revise cada evidência em um único espaço.</p></div><div className="metric"><strong>{history.length}</strong><span>sessões recentes</span></div></header>
    {showUsers&&currentUser?.role==="admin"&&<section className="user-admin"><div className="panel-title"><div><h2>Usuários internos</h2><p>Crie acessos individuais. Cada jogador visualiza somente as próprias sessões.</p></div><span>{userMessage}</span></div><form onSubmit={createInternalUser}><input name="email" type="email" placeholder="E-mail do usuário" autoComplete="off" required/><input name="password" type="password" placeholder="Senha inicial (mínimo 8 caracteres)" autoComplete="new-password" minLength={8} required/><select name="role" defaultValue="player"><option value="player">Jogador</option><option value="admin">Administrador</option></select><button>Criar login</button></form><div className="user-list">{users.map(user=><article key={user.email}><div><b>{user.email}</b><span>{user.role==="admin"?"Administrador":"Jogador"} · {user.active?"Ativo":"Inativo"}</span></div><div><button onClick={()=>void resetInternalPassword(user.email)}>Redefinir senha</button><button disabled={user.email===currentUser.email} className={user.active?"deactivate":"activate"} onClick={()=>void toggleInternalUser(user.email)}>{user.active?"Desativar":"Ativar"}</button></div></article>)}</div></section>}
    <section className="global-kpis"><article><strong>{totalHours.toFixed(1)}h</strong><span>Tempo gravado</span></article><article><strong>{totalHands}</strong><span>Mãos completas</span></article><article><strong>{totalPartial}</strong><span>Em quarentena</span></article><article><strong>{finalizedPercent}%</strong><span>Revisões finalizadas</span></article><a href="/v1/sessions/export" download>Exportar sessões</a></section>
    <section className="workspace"><aside><form key="upload" className="upload-card" onSubmit={submit}><h2>Nova sessão</h2><label>Gravação encerrada<input name="video" type="file" accept="video/mp4,video/quicktime,video/x-matroska,video/webm" required/></label><label>Nome do torneio (opcional)<input name="tournament_name" autoComplete="off" data-lpignore="true" data-1p-ignore placeholder="Ex.: 20K Garantido"/></label><button disabled={state==="sending"}>{state==="sending"?"Enviando…":"Enviar sessão"}</button><p className={`status ${state}`}>{message}</p></form>
      <div className="sessions"><h2>Sessões</h2><div className="session-tools"><input value={sessionSearch} onChange={e=>setSessionSearch(e.target.value)} placeholder="Buscar torneio ou tag…"/><select value={sessionFilter} onChange={e=>setSessionFilter(e.target.value)}><option value="all">Todos os estados</option><option value="clips_ready_for_review">Prontos</option><option value="failed">Com falha</option><option value="uploaded">Enviados</option></select><select value={dateFilter} onChange={e=>setDateFilter(e.target.value)}><option value="all">Todo período</option><option value="7d">Últimos 7 dias</option><option value="30d">Últimos 30 dias</option><option value="90d">Últimos 90 dias</option></select><select value={sortOrder} onChange={e=>setSortOrder(e.target.value)}><option value="newest">Mais recentes</option><option value="oldest">Mais antigas</option><option value="hands">Mais mãos</option></select><label><input type="checkbox" checked={favoritesOnly} onChange={e=>setFavoritesOnly(e.target.checked)}/> Somente favoritas</label><label><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/> Mostrar arquivadas</label></div>{visibleHistory.map(x=><button className={processing?.session_id===x.id?"active":""} key={x.id} onClick={()=>void followProcessing(x.id)}><strong>{x.favorite?"★ ":""}{x.tournament_name||"Sessão PPPoker"}</strong><span>{new Date(x.created_at).toLocaleString("pt-BR")}</span><span className={`session-badge ${x.processing_status}`}>{x.review_finalized?"REVISÃO FINALIZADA":labels[x.processing_status]||x.processing_status}</span><small>{x.complete_hands} completas · {x.partial_hands} incompletas · {(x.duration_seconds/60).toFixed(0)} min</small>{(x.session_tags??[]).length>0&&<small>#{x.session_tags.join(" #")}</small>}</button>)}</div></aside>
      <section className="review">{!processing?<div className="empty"><span>◇</span><h2>Selecione ou envie uma sessão</h2><p>A linha do tempo, os clipes e as evidências aparecerão aqui.</p></div>:<>
        <div className="review-head"><div><p className="eyebrow">SESSÃO {processing.session_id.slice(0,8)}</p><h2>{labels[processing.status]||processing.status}</h2></div>{manifest.metadata&&<div className="meta"><span>{Math.round(manifest.metadata.duration_seconds/60)} min</span><span>{manifest.metadata.video.width}×{manifest.metadata.video.height}</span><span>{manifest.metadata.video.codec}</span></div>}</div>
        <div className="session-admin"><button onClick={()=>void renameSession()}>Editar torneio</button><button className={review.favorite?"active":""} onClick={()=>void saveReview({...review,favorite:!review.favorite})}>{review.favorite?"★ Favorita":"☆ Favoritar"}</button><button className={review.archived?"active":""} onClick={()=>void saveReview({...review,archived:!review.archived})}>{review.archived?"Restaurar":"Arquivar"}</button><input value={sessionTagsText} placeholder="Tags da sessão, separadas por vírgula" onChange={e=>setSessionTagsText(e.target.value)}/><button onClick={()=>void saveReview({...review,session_tags:sessionTagsText.split(",").map(x=>x.trim()).filter(Boolean).slice(0,12)})}>Salvar tags</button></div>
        {manifest.metadata&&<div className="file-details"><span><b>Arquivo</b>{history.find(x=>x.id===processing.session_id)?.original_filename||"Gravação"}</span><span><b>Tamanho</b>{(manifest.metadata.size_bytes/1048576).toFixed(1)} MB</span><span><b>Frames</b>{manifest.segmentation?.frame_count??timeline.length}</span><span><b>Áudio</b>{manifest.metadata.has_audio?"Sim":"Não"}</span></div>}
        {processing.status==="failed"&&<div className="processing-error"><div><b>O processamento encontrou uma falha</b><span>{manifest.error||"Erro não identificado. Consulte os logs do worker."}</span></div><button onClick={()=>void retrySession()}>Reprocessar sessão</button></div>}
        <div className="stepper">{steps.map((s,i)=><div className={i<current?"done":i===current?"current":""} key={s}><i>{i<current?"✓":i+1}</i><span>{labels[s]}</span></div>)}</div>
        {manifest.hand_detection?.summary&&<div className="summary"><article><strong>{manifest.hand_detection.summary.complete_hands}</strong><span>Mãos completas</span></article><article><strong>{manifest.hand_detection.summary.partial}</strong><span>Em quarentena</span></article><article><strong>{manifest.hand_detection.summary.with_lobby}</strong><span>Com Lobby</span></article><article><strong>{manifest.rabbit_detection?.confirmed_events??0}</strong><span>Coelhos confirmados</span></article></div>}
        <div className="review-progress"><div><b>{review.finalized?"Revisão finalizada":`${reviewPercent}% revisado`}</b><span>{reviewDone} de {reviewTargets} decisões</span></div><i><span style={{width:`${review.finalized?100:reviewPercent}%`}}/></i><div><a href={`/v1/sessions/${processing.session_id}/review/export`} download>Exportar JSON</a><button disabled={reviewTargets>0&&reviewDone<reviewTargets} onClick={()=>void saveReview({...review,finalized:!review.finalized})}>{review.finalized?"Reabrir revisão":"Finalizar revisão"}</button></div></div>
        <div className="workspace-tabs">{[["overview","Visão geral"],["hands",`Mãos (${hands.length})`],["context","Contexto"],["evidence","Evidências"]].map(([id,name])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{name}</button>)}</div>
        {tab==="context"&&(manifest.lobby_context??[]).length>0&&<section className="panel lobby-editor"><div className="panel-title"><div><h3>Dados confirmados do Lobby</h3><p>Corrija manualmente o OCR antes de confirmar o contexto.</p></div></div>{(manifest.lobby_context??[]).map((e:any)=>{const key=String(e.start_seconds);const candidate=e.candidates??{};const value=review.lobby_values[key]??{players:candidate.players_current&&candidate.players_total?`${candidate.players_current}/${candidate.players_total}`:"",remaining:String(candidate.players_remaining??""),average_stack:String(candidate.average_stack_bb??""),prize:String(candidate.prize_text??"")};const update=(next:LobbyValue)=>setReview({...review,lobby_values:{...review.lobby_values,[key]:next}});return <article key={`edit-${key}`}><b>Lobby · {key}s</b><div><input value={value.players} placeholder="Jogadores: 68/72" onChange={x=>update({...value,players:x.target.value})}/><input value={value.remaining} placeholder="Restantes" onChange={x=>update({...value,remaining:x.target.value})}/><input value={value.average_stack} placeholder="Stack médio em BB" onChange={x=>update({...value,average_stack:x.target.value})}/><input value={value.prize} placeholder="Premiação" onChange={x=>update({...value,prize:x.target.value})}/><button onClick={()=>void saveReview(review)}>Salvar dados</button></div></article>})}</section>}
        {tab==="context"&&<section className="panel decision-queue"><div className="panel-title"><div><h3>Fila de validação</h3><p>Suas decisões ficam salvas e não alteram a evidência original.</p></div><span>{reviewStatus}</span></div>{(manifest.lobby_context??[]).map((e:any)=><article key={`review-lobby-${e.start_seconds}`}><div><b>Lobby · {e.start_seconds}s</b><small>{review.lobby[String(e.start_seconds)]?.toUpperCase()||"PENDENTE"}</small></div><div className="review-actions"><button className={review.lobby[String(e.start_seconds)]==="confirmed"?"selected approve":"approve"} onClick={()=>void decide("lobby",String(e.start_seconds),"confirmed")}>Confirmar contexto</button><button className={review.lobby[String(e.start_seconds)]==="rejected"?"selected reject":"reject"} onClick={()=>void decide("lobby",String(e.start_seconds),"rejected")}>Descartar</button></div></article>)}{rabbits.map((r:any)=><article key={`review-${r.file}`}><div><b>Possível Coelho · {r.timestamp_seconds}s</b><small>{review.rabbits[r.file]?.toUpperCase()||"PENDENTE"}</small></div><div className="review-actions"><button className={review.rabbits[r.file]==="confirmed"?"selected approve":"approve"} onClick={()=>void decide("rabbits",r.file,"confirmed")}>Confirmar Coelho</button><button className={review.rabbits[r.file]==="rejected"?"selected reject":"reject"} onClick={()=>void decide("rabbits",r.file,"rejected")}>Descartar</button></div></article>)}</section>}
        {tab==="overview"&&<section className="panel notes-panel"><div><h3>Observações da sessão</h3><p>Registre pontos para a revisão e para o futuro Coach IA.</p></div><textarea value={review.notes} maxLength={4000} placeholder="Ex.: revisar decisões próximas da bolha…" onChange={e=>setReview({...review,notes:e.target.value})}/><div><span>{reviewStatus}</span><button onClick={()=>void saveReview(review)}>Salvar observações</button></div></section>}
        {(tab==="overview"||tab==="hands")&&clips.length>0&&<section className="panel"><div className="panel-title"><div><h3>Mãos completas</h3><p>{completeHands.length} mãos aptas para revisão pós-sessão</p></div></div><div className="clips-large">{clips.filter((c:any)=>!c.partial).map((c:any)=>{const h=hands.find((x:any)=>x.index===c.hand_index);const key=String(c.hand_index);const detail=review.hand_details[key]??{tag:"",difficulty:"",note:""};const update=(value:HandDetail)=>setReview({...review,hand_details:{...review.hand_details,[key]:value}});return <article key={c.file}><video controls preload="metadata" src={`/v1/sessions/${processing.session_id}/clips/${c.file}`}/><div className="clip-info"><strong>Mão {c.hand_index}</strong><span>{h?.start_seconds}s–{h?.end_seconds}s · confiança {Math.round((h?.confidence??0)*100)}%</span><em>{review.hands[key]?review.hands[key].toUpperCase():"AGUARDANDO REVISÃO"}</em></div><div className="hand-editor"><input value={detail.tag} maxLength={80} placeholder="Tag/spot: ICM, 3bet, BvB…" onChange={e=>update({...detail,tag:e.target.value})}/><select value={detail.difficulty} onChange={e=>update({...detail,difficulty:e.target.value})}><option value="">Dificuldade</option><option value="easy">Fácil</option><option value="medium">Média</option><option value="hard">Difícil</option></select><textarea value={detail.note} maxLength={1000} placeholder="Observação desta mão…" onChange={e=>update({...detail,note:e.target.value})}/><button onClick={()=>void saveReview(review)}>Salvar detalhes</button></div><div className="review-actions"><button className={review.hands[key]==="approved"?"selected approve":"approve"} onClick={()=>void decide("hands",key,"approved")}>Aprovar mão</button><button className={review.hands[key]==="rejected"?"selected reject":"reject"} onClick={()=>void decide("hands",key,"rejected")}>Descartar</button></div></article>})}</div></section>}
        {(tab==="overview"||tab==="hands")&&quarantine.length>0&&<section className="panel quarantine"><div className="panel-title"><div><h3>Quarentena</h3><p>Trechos incompletos nunca entram na análise técnica automaticamente.</p></div></div><div className="hand-list">{quarantine.map((h:any)=><article key={h.index}><b>Mão candidata {h.index}</b><span>{h.start_seconds}s–{h.end_seconds}s</span><em>{(h.reasons??[]).map((r:string)=>r.replaceAll("_"," ")).join(" · ")}</em></article>)}</div></section>}
        {(tab==="overview"||tab==="context")&&(rabbits.length>0||(manifest.lobby_context??[]).length>0)&&<section className="panel"><div className="panel-title"><div><h3>Contexto do torneio</h3><p>Campos extraídos são candidatos até a conferência visual.</p></div></div><div className="evidence-grid">{(manifest.lobby_context??[]).map((e:any,i:number)=>{const c=e.candidates??{};return <article key={`l${i}`}><img src={`/v1/sessions/${processing.session_id}/frames/${e.representative_frame||e.frames[0]}`} alt="Lobby"/><b>Lobby · {e.start_seconds}s</b><div className="context-fields"><span><small>Jogadores</small>{c.players_current&&c.players_total?`${c.players_current}/${c.players_total}`:"—"}</span><span><small>Restantes</small>{c.players_remaining??"—"}</span><span><small>Stack médio</small>{c.average_stack_bb?`${c.average_stack_bb} BB`:"—"}</span><span><small>Premiação</small>{c.prize_text??"—"}</span></div><details><summary>Ver OCR original</summary><p>{e.ocr?.raw_text||"Texto ainda não reconhecido"}</p></details><em>CONTEXTO NÃO VERIFICADO</em></article>})}{rabbits.map((r:any)=><article key={r.file}><img src={`/v1/sessions/${processing.session_id}/evidence/${r.file}`} alt="Faixa candidata de Coelho"/><b>Possível Coelho · {r.timestamp_seconds}s</b><details><summary>Ver texto capturado</summary><p>{r.ocr?.raw_text||"Texto não encontrado"}</p></details><em className={r.confirmed?"confirmed":""}>{r.confirmed?"CONFIRMADO: PAGOU O COELHO":"TEXTO PARCIAL · REVISAR"}</em></article>)}</div></section>}
        {(tab==="overview"||tab==="evidence")&&<section className="panel"><div className="panel-title"><div><h3>Linha do tempo e evidências</h3><p>{filtered.length} imagens · evidência visual original</p></div><div className="filters">{["all","table","lobby","transition","unknown"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x==="all"?"Todas":x}</button>)}</div></div><div className="timeline-large">{filtered.map((f:any)=><figure key={f.file}><img src={`/v1/sessions/${processing.session_id}/frames/${f.file}`} alt={`${f.screen_type} em ${f.timestamp_seconds}s`}/><figcaption><b>{f.screen_type}</b><span>{f.timestamp_seconds}s · S{f.segment_id}</span></figcaption></figure>)}</div></section>}
      </>}</section></section></>}
    <footer>Coach IA · testes internos · análise exclusivamente pós-sessão · v3.0.0</footer></main>;
}
